### PR TITLE
Get token refactor

### PR DESCRIPTION
**Pull request by danwkennedy**
Makes finding a token a little more flexible.

### CODE REVIEW

**Comment by ddproxy** [comment]
I like this, just had to implement the same function through getToken. 👍

**Comment by nfantone** [comment]
@danwkennedy LGTM. Very. Let's wait on @stiang to review it.

**Comment by stiang** [comment]
Awesome, merged! Thanks, @danwkennedy 🍰

**Comment by brendanvinson** [comment]
Has this been released? NPM is installing 1.2, but the latest tagged here is 1.1.1 so I'm unclear.

**Comment by ddproxy** [comment]
@stiang ^

**Comment by stiang** [comment]
Yes, it’s released. I pushed it to npm, but didn’t create a release here. I’ve done that now.

**Pull request merged**
