### PR TITLE
Update the repo 🚀 !

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
- update the `.gitignore` file.
- avoid `package-lock.json` file.
- update the `README.md` file.
- update all dependencies.
- fix the `LICENSE` file.
- update the pipeline `.travis.yml`.
- clean the test code by remove all unused vars .
- add all contributors to `package.json` file.
- fix the version in `package.json` file by sync with the release tag [here](https://github.com/koajs/jwt/releases).

> can go to next version 😊 ❤️ !

### CODE REVIEW

**Comment by 3imed-jaberi** [comment]
Hi @sdd, Travis has failed due to updating the p-any from version 1.1.0 to 2.1.0 .. the package now supports Node.js 8+ .. 

Is it important to maintain compatibility with Node.js 7.6.0 🤔 !!

**Comment by niftylettuce** [comment]
@3imed-jaberi 	what's status here? give me a rundown of what I need to do or if this is still pending more changes?

**Comment by niftylettuce** [comment]
Also @3imed-jaberi 	I have IRC, Riot.im, Signal, Telegram, and other means of real-time communication.  Email me niftylettuce@gmail.com.

**Comment by niftylettuce** [comment]
@haoxins Can you grant me npm access? `niftylettuce` is my username.

```sh
λ ~/Projects/jwt/ master np

Publish a new version of koa-jwt (current: 3.6.0)

Commits:
- chore: bump deps, update yarn.lock  c680e0c
- Update the repo 🚀 ! (#167)  98f2d7d
- update README.md 📋 ..  4b40038
- Update auth0 blog link to GitHub source (#169)  9469ecb
- The missprint in code example  30bb2dc
- Update auth0 blog link to GitHub source  bcc7868
-  node 8+ support 👍🏻 ..  d2ec441
-  sync with latest release tag --3.6.0 🎗 ..  9729b1f
-  better --stuctrue 🎗 ..  69d83d3
-  add all contributors to pkg.json 📋 ..  cc68dbb
-  update some depen. 🪁..  999c0bb
-  update the CI pipeline 🎲 ..  65a65c0
-  use string template over + 📍..  5187dc3
-  use template string over + | ' over '' 📌 ..  83d896c
-  remove unused vars ❌ ..  02bded8
-  semi-colon & arrow func update 🎯 ..  e9b5d09
-  disable package-lock.json 🚫 ..  e90d2a9
-  update .gitignore file 🐞 ..  08ef6ba
-  update LICENSE 🔏 ..  d37959d
-  update README.md 📇 ..  b272379
- Allow String arrays fro Options.issuer  ceafb45
- Merge pull request #153 from bmisiak/patch-1  e89996a
- koa-unless path supports strings, RegExps and arrays of these.  cae6fdb
- Merge pull request #143 from sjmcdowall/master  fb86a8b
- Merge pull request #148 from hassan-jahan/master  37718e4
- Merge pull request #149 from jakesjews/master  045adb9
- update jsonwebtoken to 8.5.1  74b5dec
- Update README.md  fd469a0
- Update README.md  cb9f8da
- error handling when passthrough is on  2abdc93
- Fix audience definition to match RFC  6cc4067
- Merge pull request #140 from feimosi/patch-1  51efb1f
- Add missing typing for `.unless` method  4208ea0

Commit Range:
v3.5.1...master

? Select semver increment or specify new version minor 	3.7.0

  ❯ Prerequisite check
    ✔ Ping npm registry
    ✔ Check npm version
    ✔ Check yarn version
    ✖ Verify user is authenticated
      → You do not have write permissions required to publish this package.
      Check git version
      Check git remote
      Validate version
      Check for pre-release version
      Check git tag existence
    Git
    Cleanup
    Installing dependencies using Yarn
    Running tests using Yarn
    Bumping version using Yarn
    Publishing package using Yarn
    Pushing tags
    Creating release draft on GitHub

✖ You do not have write permissions required to publish this package.
```

**Comment by haoxins** [comment]
https://www.npmjs.com/package/koa-jwt
I can't 😢

**Comment by haoxins** [comment]
https://www.npmjs.com/~stiang
https://www.npmjs.com/~sc0ttyd

**Pull request merged**
