### PR TITLE
Support multiple secrets

### PR DESCRIPTION
**Pull request by ferguscan**

### CODE REVIEW

**Comment by ferguscan** [comment]
This change allows servers to use rolling shared secrets, or to concurrently support Auth0 authentication (via PEM file), in addition to a shared secret (or public/private key pair) used for self-signed JWTs.

**Comment by sdd** [comment]
@ferguscan I've been able to address the minor points in the review by using the GitHub merge conflict resolution tool, so no work is needed on your side. I'll change the review to approved.

**Comment by sjmcdowall** [comment]
Welcome back @sdd  !!!!

**Comment by sdd** [comment]
Oh - I didn't spot the Promise.any(). That's why you had Bluebird. 🤦‍♂️ 

I'll add https://github.com/sindresorhus/p-any instead as it is much more lightweight than Bluebird as it  uses native promises.

**Comment by sdd** [comment]
Thanks for the rapid changes. I made a final change: I think that it is most likely that in the situation where a secret provider function would be used in conjunction with multiple secrets, a single function returning an array of secrets would make more sense than an array of functions that each return a single secret.

I'll merge this now and publish it as v3.5.0.

**Pull request merged**
