### PR TITLE
Change "Invalid secret" status code to 500

### PR DESCRIPTION
**Pull request by Dremora**
It's a server configuration error, so this should be reflected by the status code.

### CODE REVIEW

**Comment by felixfbecker** [comment]
I agree

**Comment by sc0ttyd** [comment]
Also agree.

**Comment by tejasmanohar** [comment]
Unless an RFC or similar says that this validation must return this certain content back to the client, I'd rather throw a real error object here so that the client can catch and re-throw this error as/if needed.

**Comment by felixfbecker** [comment]
@tejasmanohar But that's what he is doing...

**Comment by stiang** [comment]
Agreed, merged. Thanks!

**Pull request merged**
