### PR TITLE
Add support to query string parameter token

### PR DESCRIPTION
**Pull request by peteyy**
Some API-s allow authentication via query string parameter, that allows faster interaction with tools like curl.

### CODE REVIEW

**Comment by hekike** [comment]
Any chance to merge it?

**Comment by sc0ttyd** [comment]
I think I would prefer this if the query string behaviour only happens if query is present in config options: 

i.e., instead of this:
```
 } else if (this.query && this.query.access_token) {
+      token = this.query.access_token;
```

It was this:
```
 } else if (opts.query && this.query && this.query[opts.query]) {
+      token = this.query[opts.query];
```

This would also allow you to specify which query param is used rather than hard-coding it to access_token

**Comment by burkhardr** [comment]
As suggested in https://github.com/stiang/koa-jwt/issues/30, I'd prefer this to be a more generic `getToken()` function.

We'd like to store the token in a redux store and could really do with the flexibility.

**Comment by stiang** [comment]
Sorry about the delay on this. I agree that the getToken solution is probably preferrable. Any chance of a PR with tests? Will merge :)

**Comment by nfantone** [comment]
@stiang Now that #30 was merged, shall we close this?

**Comment by sc0ttyd** [comment]
Closing. See https://github.com/koajs/jwt/issues/30

**Pull request closed without merging**
